// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "somethingWrongHappend": "حدث خطأ ما",
  "ok": "موافق",
  "cancel": "إلغاء",
  "error": "خطأ",
  "success": "نجاح",
  "warning": "تحذير",
  "emailAlreadyInUse": "هذا البريد الإلكتروني مستخدم من قبل",
  "userNotFound": "المستخدم غير موجود",
  "wrongPassword": "كلمة المرور خاطئة",
  "welcome": "مرحباً",
  "signInToContinue": "تسجيل الدخول للمتابعة",
  "signUp": "تسجيل",
  "singIn": "تسجيل الدخول",
  "or": "أو",
  "forgotPassword": "نسيت كلمة المرور؟",
  "email": "البريد الإلكتروني",
  "password": "كلمة المرور",
  "confirmPassword": "تأكيد كلمة المرور",
  "name": "الاسم",
  "phone": "رقم الهاتف",
  "invalid": "غير صالح",
  "wrongEmailOrPassword": "خطأ في البريد الإلكتروني أو كلمة المرور",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "signInWithGoogle": "تسجيل الدخول بواسطة جوجل",
  "noAccount": "ليس لديك حساب؟",
  "createOne": "إنشاء حساب",
  "noInternetConnection": "لا يوجد اتصال بالإنترنت",
  "youShouldSelectGoogleAccount": "يجب تحديد حساب جوجل",
  "signout": "تسجيل الخروج",
  "atLeast": "على الأقل - حرف",
  "normalLetters": "- حرف",
  "uppercaseLetters": "- حرف كبير",
  "lowercaseLetters": "- حرف صغير",
  "numericCharacters": "- رقم",
  "specialCharacters": "- رمز",
  "noProducts": "لا يوجد منتجات",
  "epg": "جنية",
  "electronics": "إلكترونيات",
  "jewelery": "مجهورات",
  "menClothing": "ملابس رجالي",
  "womenClothing": "ملابس حريمي",
  "home": "الرئيسية",
  "categories": "الفئات",
  "products": "المنتجات",
  "all": "الكل",
  "cart": "السلة",
  "total": "المجموع",
  "count": "عدد",
  "checkout": "حاسب",
  "youMustBeAuthenticated": "يجب عليك تسجيل الدخول",
  "settings": "الإعدادات",
  "language": "اللغة",
  "theme": "المظهر",
  "logout": "تسجيل الخروج",
  "changePassword": "تغيير كلمة المرور",
  "oldPassword": "كلمة المرور القديمة",
  "newPassword": "كلمة المرور الجديدة",
  "confirmNewPassword": "تأكيد كلمة المرور الجديدة",
  "updateProfile": "تحديث الملف الشخصي",
  "profile": "الملف الشخصي",
  "emailAddress": "عنوان البريد الإلكتروني",
  "update": "تحديث",
  "privacyPolicy": "سياسة الخصوصية",
  "contactUs": "اتصل بنا",
  "addresses": "العناوين",
  "checkInternetConnection": "تحقق من اتصال الانترنت",
  "internalServerError": "خطأ في الخادم الداخلي",
  "unknown": "غير معروف",
  "databaseError": "خطأ في قاعدة البيانات",
  "unknownError": "خطأ غير معروف",
  "unauthorized": "غير مصرح",
  "noData": "لا يوجد بيانات",
  "invalidInput": "مدخل غير صالح",
  "cacheError": "خطأ في الذاكرة المؤقتة"
};
static const Map<String,dynamic> en = {
  "somethingWrongHappend": "Something wrong happened",
  "ok": "OK",
  "cancel": "Cancel",
  "error": "Error",
  "success": "Success",
  "warning": "Warning",
  "emailAlreadyInUse": "The account already exists for that email",
  "userNotFound": "User not found",
  "wrongPassword": "Wrong password",
  "welcome": "Welcome",
  "signInToContinue": "Sign in to continue",
  "signUp": "Sign up",
  "singIn": "Sign in",
  "or": "or",
  "forgotPassword": "Forgot password?",
  "email": "Email",
  "password": "Password",
  "confirmPassword": "Confirm password",
  "name": "Name",
  "phone": "Phone",
  "invalid": "Invalid",
  "wrongEmailOrPassword": "Wrong email or password",
  "resetPassword": "Reset password",
  "signInWithGoogle": "Sign in with Google",
  "noAccount": "Don't have an account?",
  "createOne": "Create one",
  "noInternetConnection": "No internet connection",
  "youShouldSelectGoogleAccount": "You should select Google account",
  "signout": "Sign out",
  "atLeast": "At least - character",
  "normalLetters": "- Letter",
  "uppercaseLetters": "- Uppercase letter",
  "lowercaseLetters": "- Lowercase letter",
  "numericCharacters": "- Numeric character",
  "specialCharacters": "- Special character",
  "noProducts": "No products found",
  "epg": "EPG",
  "electronics": "electronics",
  "jewelery": "jewelery",
  "menClothing": "men's clothing",
  "womenClothing": "women's clothing",
  "home": "Home",
  "categories": "Categories",
  "products": "Products",
  "all": "All",
  "cart": "Cart",
  "total": "Total",
  "count": "Count",
  "checkout": "Checkout",
  "youMustBeAuthenticated": "You must be authenticated",
  "settings": "Settings",
  "language": "Language",
  "theme": "Theme",
  "logout": "Logout",
  "changePassword": "Change password",
  "oldPassword": "Old password",
  "newPassword": "New password",
  "confirmNewPassword": "Confirm new password",
  "updateProfile": "Update profile",
  "profile": "Profile",
  "emailAddress": "Email address",
  "update": "Update",
  "privacyPolicy": "Privacy policy",
  "contactUs": "Contact us",
  "addresses": "Addresses",
  "checkInternetConnection": "Check internet connection",
  "internalServerError": "Internal server error",
  "unknown": "Unknown",
  "databaseError": "Database error",
  "unauthorized": "Unauthorized",
  "forbidden": "Forbidden",
  "notFound": "Not found",
  "tooManyRequests": "Too many requests",
  "serverError": "Server error",
  "invalidEmail": "Invalid email",
  "noData": "No data",
  "invalidInput": "Invalid input",
  "cacheError": "Cache error"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
