// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE5prhmk_-8CGS9MX-e6X4ToQZdLgERM',
    appId: '1:274202204563:web:b836f4873223ce84b97066',
    messagingSenderId: '274202204563',
    projectId: 'shoppingo-4ce70',
    authDomain: 'shoppingo-4ce70.firebaseapp.com',
    storageBucket: 'shoppingo-4ce70.appspot.com',
    measurementId: 'G-9QRPDTMMPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcYzBLdfcHhfysLd9qNDwc2sD1CCP8uk',
    appId: '1:274202204563:android:2fd5881d3998f976b97066',
    messagingSenderId: '274202204563',
    projectId: 'shoppingo-4ce70',
    storageBucket: 'shoppingo-4ce70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5FQGouoRuPX6bAlIw6Fod8uFm6mQXus',
    appId: '1:274202204563:ios:2db51c690b5085b2b97066',
    messagingSenderId: '274202204563',
    projectId: 'shoppingo-4ce70',
    storageBucket: 'shoppingo-4ce70.appspot.com',
    iosBundleId: 'com.example.shopink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC5FQGouoRuPX6bAlIw6Fod8uFm6mQXus',
    appId: '1:274202204563:ios:2db51c690b5085b2b97066',
    messagingSenderId: '274202204563',
    projectId: 'shoppingo-4ce70',
    storageBucket: 'shoppingo-4ce70.appspot.com',
    iosBundleId: 'com.example.shopink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCE5prhmk_-8CGS9MX-e6X4ToQZdLgERM',
    appId: '1:274202204563:web:f02ccd1a739ac27cb97066',
    messagingSenderId: '274202204563',
    projectId: 'shoppingo-4ce70',
    authDomain: 'shoppingo-4ce70.firebaseapp.com',
    storageBucket: 'shoppingo-4ce70.appspot.com',
    measurementId: 'G-P5ZFJM3EFW',
  );
}
